source 'https://rubygems.org'

gem 'sinatra'        , '2.0.0'
gem 'sinatra-contrib', '2.0.0'
gem 'mongoid'        , '7.0.0.beta'
gem 'arkaan'         , '0.5.7'
gem 'draper'         , '3.0.1'
gem 'faraday'        , '0.13.1'
gem 'pry'            , '0.11.1'